### ISSUE TITLE
Build fails on macOS / Darwin: struct stat64 is deprecated

### ISSUE THREAD

**Issue by franckr** [NXPmicro/mfgtools#274]
Build on macOS Big Sur 11.4 (20F71) on Apple M1:

```
[...]/mfgtools/libuuu/buffer.cpp:132:17: error: variable has incomplete type 'struct stat64'
                struct stat64 st;
[...]
```

`man stat64`:
```
TRANSITIONAL DESCRIPTION (NOW DEPRECATED)
     The fstat64, lstat64 and stat64 routines are equivalent to their corre-
     sponding non-64-suffixed routine, when 64-bit inodes are in effect.  They
     were added before there was support for the symbol variants, and so are
     now deprecated.  Instead of using these, set the _DARWIN_USE_64_BIT_INODE
     macro before including header files to force 64-bit inode support.

     The stat64 structure used by these deprecated routines is the same as the
     stat structure when 64-bit inodes are in effect (see above).
```
